  global:
  resolve_timeout: 5m

route:
  receiver: slack_notifications

receivers:
  - name: slack_notifications
    slack_configs:
      - send_resolved: true
        api_url: "https://hooks.slack.com/services/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"
        channel: "#devops-alerts"
        username: "Prometheus Alert Bot"
        text: |-
          *Alert:* {{ .CommonLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}
          *Instance:* {{ .CommonLabels.instance }}
          *Description:* {{ .CommonAnnotations.description }}
